export type ReadingVisualKind = "astrology" | "tarot";

export interface ReadingVisualConfig {
  slug: string;
  kind: ReadingVisualKind;
  kicker: string;
  motif: string;
  title: string;
  accent: string;
  secondary: string;
  glow: string;
  markers: [string, string, string, string];
  detailLabels: [string, string, string];
  planetImages?: string[];
  cardCount?: number;
}

const PLANET_IMAGES = {
  chiron: "/images/horoscope-zodiac/chiron.png",
  jupiter: "/images/horoscope-zodiac/jupiter.png",
  mars: "/images/horoscope-zodiac/mars.png",
  mercury: "/images/horoscope-zodiac/mercury.png",
  moon: "/images/horoscope-zodiac/moon.png",
  node: "/images/horoscope-zodiac/node.png",
  saturn: "/images/horoscope-zodiac/saturn.png",
  sun: "/images/horoscope-zodiac/sun.png",
  uranus: "/images/horoscope-zodiac/uranus.png",
  venus: "/images/horoscope-zodiac/venus.png",
};

const READING_VISUALS: Record<string, ReadingVisualConfig> = {
  "nativity-birth-chart": {
    slug: "nativity-birth-chart",
    kind: "astrology",
    kicker: "Birth map",
    motif: "Natal wheel",
    title: "Houses, angles, rulers",
    accent: "#f1d37a",
    secondary: "#66d9c7",
    glow: "rgba(102, 217, 199, 0.22)",
    markers: ["Asc", "Moon", "Sun", "MC"],
    detailLabels: ["Birth moment", "Chart ruler", "Life pattern"],
    planetImages: [PLANET_IMAGES.sun, PLANET_IMAGES.moon, PLANET_IMAGES.mercury],
  },
  "solar-return": {
    slug: "solar-return",
    kind: "astrology",
    kicker: "Year map",
    motif: "Solar arc",
    title: "Annual focus and timing",
    accent: "#ffd166",
    secondary: "#ff7a59",
    glow: "rgba(255, 122, 89, 0.24)",
    markers: ["Sun", "Asc", "Peak", "Close"],
    detailLabels: ["Birthday chart", "Year theme", "Timing windows"],
    planetImages: [PLANET_IMAGES.sun],
  },
  "monthly-transits-lunar-return": {
    slug: "monthly-transits-lunar-return",
    kind: "astrology",
    kicker: "Lunar cycle",
    motif: "Monthly weather",
    title: "Moon timing and transit rhythm",
    accent: "#d8e7ff",
    secondary: "#7aa7ff",
    glow: "rgba(122, 167, 255, 0.24)",
    markers: ["New", "Build", "Full", "Release"],
    detailLabels: ["Lunar return", "Transit triggers", "Monthly plan"],
    planetImages: [PLANET_IMAGES.moon, PLANET_IMAGES.mercury],
  },
  "saturn-return": {
    slug: "saturn-return",
    kind: "astrology",
    kicker: "Saturn gate",
    motif: "Maturity cycle",
    title: "Commitment, work, and structure",
    accent: "#d4b483",
    secondary: "#8ea4c9",
    glow: "rgba(142, 164, 201, 0.22)",
    markers: ["Duty", "Limit", "Craft", "Authority"],
    detailLabels: ["Return phase", "Pressure point", "Next structure"],
    planetImages: [PLANET_IMAGES.saturn],
  },
  "jupiter-return": {
    slug: "jupiter-return",
    kind: "astrology",
    kicker: "Jupiter arc",
    motif: "Expansion map",
    title: "Opportunity, teaching, and growth",
    accent: "#f6c177",
    secondary: "#8bdc9b",
    glow: "rgba(139, 220, 155, 0.22)",
    markers: ["Growth", "Mentor", "Faith", "Reach"],
    detailLabels: ["12-year cycle", "Open doors", "Next leap"],
    planetImages: [PLANET_IMAGES.jupiter],
  },
  "weekly-transits": {
    slug: "weekly-transits",
    kind: "astrology",
    kicker: "Transit weather",
    motif: "Week ahead",
    title: "Daily choices and aspect timing",
    accent: "#c9a84c",
    secondary: "#9be7ff",
    glow: "rgba(155, 231, 255, 0.2)",
    markers: ["Mon", "Wed", "Fri", "Sun"],
    detailLabels: ["Planet shifts", "Best windows", "Weekly focus"],
    planetImages: [PLANET_IMAGES.mercury, PLANET_IMAGES.moon, PLANET_IMAGES.mars],
  },
  "romantic-relationships": {
    slug: "romantic-relationships",
    kind: "astrology",
    kicker: "Synastry field",
    motif: "Romance overlay",
    title: "Attraction, needs, and timing",
    accent: "#f6a7b8",
    secondary: "#c9a84c",
    glow: "rgba(246, 167, 184, 0.22)",
    markers: ["Venus", "Moon", "Mars", "Saturn"],
    detailLabels: ["Compatibility", "Attachment style", "Growth edge"],
    planetImages: [PLANET_IMAGES.venus, PLANET_IMAGES.moon, PLANET_IMAGES.mars],
  },
  "friendship-relationships": {
    slug: "friendship-relationships",
    kind: "astrology",
    kicker: "Bond map",
    motif: "Friendship matrix",
    title: "Trust, values, and shared momentum",
    accent: "#9bd4bc",
    secondary: "#f1d37a",
    glow: "rgba(155, 212, 188, 0.22)",
    markers: ["Trust", "Values", "Flow", "Repair"],
    detailLabels: ["Shared language", "Support pattern", "Long-term fit"],
    planetImages: [PLANET_IMAGES.mercury, PLANET_IMAGES.venus],
  },
  "business-relationship": {
    slug: "business-relationship",
    kind: "astrology",
    kicker: "Alliance map",
    motif: "Work partnership",
    title: "Roles, risk, and growth strategy",
    accent: "#b9c6ff",
    secondary: "#f6c177",
    glow: "rgba(185, 198, 255, 0.22)",
    markers: ["Role", "Risk", "Scale", "Terms"],
    detailLabels: ["Shared mission", "Decision style", "Growth path"],
    planetImages: [PLANET_IMAGES.saturn, PLANET_IMAGES.jupiter, PLANET_IMAGES.mercury],
  },
  "predictive-event-horary": {
    slug: "predictive-event-horary",
    kind: "astrology",
    kicker: "Question chart",
    motif: "Horary moment",
    title: "The chart cast for one question",
    accent: "#f1d37a",
    secondary: "#a78bfa",
    glow: "rgba(167, 139, 250, 0.22)",
    markers: ["Hour", "Asc", "Moon", "Answer"],
    detailLabels: ["Question time", "Ruling planet", "Likely outcome"],
    planetImages: [PLANET_IMAGES.mercury, PLANET_IMAGES.moon],
  },
  "mars-return": {
    slug: "mars-return",
    kind: "astrology",
    kicker: "Action return",
    motif: "Mars ignition",
    title: "Drive, conflict, and momentum",
    accent: "#ff6b5f",
    secondary: "#f1d37a",
    glow: "rgba(255, 107, 95, 0.25)",
    markers: ["Drive", "Heat", "Edge", "Move"],
    detailLabels: ["Energy cycle", "Conflict pattern", "Action plan"],
    planetImages: [PLANET_IMAGES.mars],
  },
  "uranus-opposition": {
    slug: "uranus-opposition",
    kind: "astrology",
    kicker: "Awakening axis",
    motif: "Uranus break",
    title: "Freedom, disruption, and reinvention",
    accent: "#8be9fd",
    secondary: "#c9a84c",
    glow: "rgba(139, 233, 253, 0.24)",
    markers: ["Break", "Free", "Shock", "Future"],
    detailLabels: ["Opposition axis", "Life reset", "New direction"],
    planetImages: [PLANET_IMAGES.uranus],
  },
  "3-card-basic-question-spread": {
    slug: "3-card-basic-question-spread",
    kind: "tarot",
    kicker: "Three cards",
    motif: "Quick signal",
    title: "Situation, choice, next step",
    accent: "#f1d37a",
    secondary: "#ff9f7a",
    glow: "rgba(255, 159, 122, 0.22)",
    markers: ["Now", "Block", "Move", "Result"],
    detailLabels: ["Clear question", "Direct answer", "Next action"],
    cardCount: 3,
  },
  "5-card-complex-question-spread": {
    slug: "5-card-complex-question-spread",
    kind: "tarot",
    kicker: "Five cards",
    motif: "Decision map",
    title: "Root, pressure, advice, outcome",
    accent: "#b9c6ff",
    secondary: "#f1d37a",
    glow: "rgba(185, 198, 255, 0.22)",
    markers: ["Root", "Block", "Advice", "Outcome"],
    detailLabels: ["Competing factors", "Hidden influence", "Best next step"],
    cardCount: 5,
  },
  "7-card-6-month-forward-review": {
    slug: "7-card-6-month-forward-review",
    kind: "tarot",
    kicker: "Seven cards",
    motif: "Six-month forecast",
    title: "Milestones, cautions, and openings",
    accent: "#9be7ff",
    secondary: "#f6c177",
    glow: "rgba(155, 231, 255, 0.22)",
    markers: ["M1", "M2", "M3", "M6"],
    detailLabels: ["Monthly arc", "Decision points", "Forward review"],
    cardCount: 7,
  },
  "7-card-horseshoe-spread-major-read": {
    slug: "7-card-horseshoe-spread-major-read",
    kind: "tarot",
    kicker: "Seven cards",
    motif: "Horseshoe arc",
    title: "Past, present, hidden forces, outcome",
    accent: "#d4b483",
    secondary: "#9bd4bc",
    glow: "rgba(155, 212, 188, 0.2)",
    markers: ["Past", "Now", "Hidden", "Outcome"],
    detailLabels: ["Pattern arc", "Outer influence", "Likely result"],
    cardCount: 7,
  },
  "10-card-relationship-spread": {
    slug: "10-card-relationship-spread",
    kind: "tarot",
    kicker: "Ten cards",
    motif: "Relationship mirror",
    title: "You, them, the bond, the path",
    accent: "#f6a7b8",
    secondary: "#8ea4c9",
    glow: "rgba(246, 167, 184, 0.22)",
    markers: ["You", "Them", "Bond", "Future"],
    detailLabels: ["Needs", "Mismatch", "Repair path"],
    cardCount: 10,
  },
  "10-card-celtic-cross-major-read": {
    slug: "10-card-celtic-cross-major-read",
    kind: "tarot",
    kicker: "Ten cards",
    motif: "Celtic cross",
    title: "Core story and probable outcome",
    accent: "#f1d37a",
    secondary: "#a78bfa",
    glow: "rgba(167, 139, 250, 0.22)",
    markers: ["Core", "Cross", "Crown", "Outcome"],
    detailLabels: ["Present pressure", "Inner truth", "Resolution path"],
    cardCount: 10,
  },
  "12-card-astrological-spread-major-read": {
    slug: "12-card-astrological-spread-major-read",
    kind: "tarot",
    kicker: "Twelve cards",
    motif: "Zodiac spread",
    title: "A house-by-house life overview",
    accent: "#c9a84c",
    secondary: "#66d9c7",
    glow: "rgba(102, 217, 199, 0.22)",
    markers: ["I", "IV", "VII", "X"],
    detailLabels: ["Life houses", "Annual themes", "Full-spectrum map"],
    cardCount: 12,
  },
};

const FALLBACK_VISUAL: ReadingVisualConfig = {
  slug: "fallback",
  kind: "astrology",
  kicker: "Reading map",
  motif: "Service focus",
  title: "Context, timing, and next steps",
  accent: "#c9a84c",
  secondary: "#66d9c7",
  glow: "rgba(102, 217, 199, 0.18)",
  markers: ["Focus", "Signal", "Choice", "Path"],
  detailLabels: ["Your question", "Reader lens", "Next step"],
  planetImages: [PLANET_IMAGES.sun],
};

export function getReadingVisualConfig(slug: string): ReadingVisualConfig {
  return READING_VISUALS[slug] ?? FALLBACK_VISUAL;
}
