import { NextRequest, NextResponse } from "next/server";
import { getAdminUser } from "@/lib/admin-auth";
import { createAdminClient } from "@/lib/supabase/admin";


// ─── POST /api/admin/users/[id]/password ─────────────────────────────────────
// action = "reset_link" → generate recovery link
// action = "force_set"  → set new password directly

export async function POST(
  req: NextRequest,
  { params }: { params: Promise<{ id: string }> }
) {
  const adminEmail = await getAdminUser();
  if (!adminEmail) return NextResponse.json({ error: "Forbidden" }, { status: 403 });

  const { id } = await params;
  const body = await req.json();
  const { action, password } = body as { action: string; password?: string };

  if (!action || !["reset_link", "force_set"].includes(action)) {
    return NextResponse.json({ error: "Invalid action" }, { status: 422 });
  }

  const admin = createAdminClient();

  if (action === "reset_link") {
    // Fetch user email first
    const { data: authUser, error: authErr } = await admin.auth.admin.getUserById(id);
    if (authErr || !authUser.user?.email) {
      return NextResponse.json({ error: "User not found" }, { status: 404 });
    }

    const { data, error } = await admin.auth.admin.generateLink({
      type: "recovery",
      email: authUser.user.email,
    });
    if (error) return NextResponse.json({ error: error.message }, { status: 500 });

    // Log the action
    await admin.from("admin_user_notes").insert({
      user_id: id,
      note: `Password reset link generated by admin ${adminEmail}`,
      role: null,
      created_by: adminEmail,
    });

    return NextResponse.json({ link: data.properties?.action_link ?? null });
  }

  if (action === "force_set") {
    if (!password || password.length < 8) {
      return NextResponse.json({ error: "Password must be at least 8 characters" }, { status: 422 });
    }

    const { error } = await admin.auth.admin.updateUserById(id, { password });
    if (error) return NextResponse.json({ error: error.message }, { status: 500 });

    // Log to admin_user_notes for audit
    await admin.from("admin_user_notes").insert({
      user_id: id,
      note: `Password force-set by admin ${adminEmail}`,
      role: null,
      created_by: adminEmail,
    });

    // Log to admin_activity_log
    await admin.from("admin_activity_log").insert({
      admin_user_id: adminEmail,
      target_user_id: id,
      action_type: "force_set_password",
      details: { note: "Password force-set by admin" },
    }).maybeSingle();

    return NextResponse.json({ success: true });
  }

  return NextResponse.json({ error: "Unknown action" }, { status: 400 });
}
