INSERT INTO marketing_content (title, description, caption_template, category, platforms, is_active) VALUES
('Natal Chart Promo', 'Promote natal chart readings', 'Discover what the stars wrote in your birth chart! Your cosmic blueprint holds the keys to understanding yourself deeply. Book a natal chart reading with me: astrologypro.com/{username}', 'astrology_general', ARRAY['facebook','twitter','whatsapp','linkedin'], TRUE),
('Tarot Insight', 'Weekly tarot wisdom', 'The cards have a message for you today. Whether it''s love, career, or spiritual growth, a tarot reading can illuminate your path forward. Book a session: astrologypro.com/{username}', 'tarot_general', ARRAY['facebook','twitter','whatsapp','linkedin'], TRUE),
('Solar Return Promo', 'Birthday season reading', 'Your birthday is more than a celebration, it''s a cosmic reset! A Solar Return reading reveals the themes of your year ahead. Discover yours: astrologypro.com/{username}', 'seasonal', ARRAY['facebook','twitter','whatsapp','linkedin'], TRUE),
('Relationship Reading', 'Synastry promo', 'Wondering about your cosmic compatibility? A relationship synastry reading reveals the strengths and challenges written in your stars. Explore your connection: astrologypro.com/{username}', 'astrology_general', ARRAY['facebook','twitter','whatsapp','linkedin'], TRUE),
('Celtic Cross Promo', 'Major tarot reading promo', 'The Celtic Cross is the most powerful tarot spread, 10 cards revealing every aspect of your situation. Ready for deep insight? Book yours: astrologypro.com/{username}', 'tarot_general', ARRAY['facebook','twitter','whatsapp','linkedin'], TRUE),
('Weekly Transits', 'Weekly astrology update', 'This week''s cosmic weather is shifting! Know what the planets have in store for you with a personalized transit reading. Stay aligned: astrologypro.com/{username}', 'astrology_general', ARRAY['facebook','twitter','whatsapp','linkedin'], TRUE),
('Spiritual Growth', 'General divination promo', 'Your soul is calling you toward something greater. Whether through the stars or the cards, divine guidance is waiting. Take the first step: astrologypro.com/{username}', 'promotional', ARRAY['facebook','twitter','whatsapp','linkedin'], TRUE),
('Saturn Return Alert', 'Saturn return awareness', 'If you''re turning 29 or 58 this year, you''re entering your Saturn Return, one of life''s most transformative passages. Navigate it with wisdom: astrologypro.com/{username}', 'seasonal', ARRAY['facebook','twitter','whatsapp','linkedin'], TRUE);
