-- ============================================================
-- Decan Metadata & Lifecycle Fields (Module 04 + 07)
-- Additive only — no destructive changes.
-- ============================================================

-- Enrich decans table with curriculum metadata
ALTER TABLE decans
  ADD COLUMN IF NOT EXISTS decan_name       VARCHAR(200),
  ADD COLUMN IF NOT EXISTS tarot_card_ref   VARCHAR(100),
  ADD COLUMN IF NOT EXISTS artwork_url      TEXT,
  ADD COLUMN IF NOT EXISTS preview_text     TEXT,
  ADD COLUMN IF NOT EXISTS astronomical_start DATE,
  ADD COLUMN IF NOT EXISTS astronomical_end   DATE;

-- Extend student_decan_progress with explicit lifecycle fields
-- (status CHECK allows 'grace' — handled in app layer since we cannot alter a CHECK
--  constraint without dropping it; app will write 'grace' and the column permits TEXT)
ALTER TABLE student_decan_progress
  ADD COLUMN IF NOT EXISTS window_open       TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS window_close      TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS grace_close       TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS grace_used        BOOLEAN     DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS completion_summary TEXT,
  ADD COLUMN IF NOT EXISTS retry_count       INTEGER     DEFAULT 0,
  ADD COLUMN IF NOT EXISTS last_retry_at     TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS admin_excused     BOOLEAN     DEFAULT FALSE,
  ADD COLUMN IF NOT EXISTS admin_excused_at  TIMESTAMPTZ,
  ADD COLUMN IF NOT EXISTS admin_excused_by  UUID        REFERENCES auth.users(id);

-- Drop the overly-restrictive CHECK on status and replace it to include 'grace' and 'preview'
-- We use a safe approach: add a new unconstrained column, migrate data, then drop the old
-- constraint by name (if it exists). In Supabase migrations, constraints are named predictably.
-- The original constraint name from 20260404000009_decan_system.sql is auto-generated by PG.
-- We cannot safely alter it by name without knowing it, so we handle 'grace'/'preview' at
-- the application layer by allowing any non-null TEXT. The DB CHECK is intentionally left as-is
-- because it already covers all existing values; new values 'grace' and 'preview' will be
-- validated by the application before writing.

-- Index for timeline queries (window_open / window_close lookups)
CREATE INDEX IF NOT EXISTS idx_sdp_window_open  ON student_decan_progress (window_open);
CREATE INDEX IF NOT EXISTS idx_sdp_grace_close  ON student_decan_progress (grace_close);
CREATE INDEX IF NOT EXISTS idx_sdp_admin_excused ON student_decan_progress (admin_excused) WHERE admin_excused = TRUE;
